SPECIES_SCORING_CONFIGS = [
    {
        "species": "bluefin",
        "label": "Bluefin Tuna",
        "season_window": "May-November",
        "notes": "Bluefin hold around structure, bait, and stable temperature zones with manageable sea state.",
        "preferred_temp_min_f": 58.0,
        "preferred_temp_max_f": 66.0,
        "ideal_chlorophyll_min": 0.22,
        "ideal_chlorophyll_max": 0.42,
        "ideal_current_min_kts": 1.1,
        "ideal_current_max_kts": 2.0,
        "temp_suitability_weight": 0.24,
        "temp_gradient_weight": 0.16,
        "structure_proximity_weight": 0.23,
        "chlorophyll_suitability_weight": 0.11,
        "current_suitability_weight": 0.13,
        "weather_fishability_weight": 0.13,
    },
    {
        "species": "yellowfin",
        "label": "Yellowfin Tuna",
        "season_window": "July-October",
        "notes": "Yellowfin prefer warmer breaks, clean water, and meaningful current edges.",
        "preferred_temp_min_f": 67.0,
        "preferred_temp_max_f": 74.0,
        "ideal_chlorophyll_min": 0.15,
        "ideal_chlorophyll_max": 0.32,
        "ideal_current_min_kts": 1.4,
        "ideal_current_max_kts": 2.3,
        "temp_suitability_weight": 0.27,
        "temp_gradient_weight": 0.2,
        "structure_proximity_weight": 0.14,
        "chlorophyll_suitability_weight": 0.14,
        "current_suitability_weight": 0.14,
        "weather_fishability_weight": 0.11,
    },
    {
        "species": "mahi",
        "label": "Mahi",
        "season_window": "June-September",
        "notes": "Mahi respond well to warmer water, cleaner color, and fishable weather around current seams.",
        "preferred_temp_min_f": 70.0,
        "preferred_temp_max_f": 78.0,
        "ideal_chlorophyll_min": 0.1,
        "ideal_chlorophyll_max": 0.24,
        "ideal_current_min_kts": 1.0,
        "ideal_current_max_kts": 1.9,
        "temp_suitability_weight": 0.29,
        "temp_gradient_weight": 0.16,
        "structure_proximity_weight": 0.09,
        "chlorophyll_suitability_weight": 0.18,
        "current_suitability_weight": 0.12,
        "weather_fishability_weight": 0.16,
    },
]

ZONE_CATALOG = [
    {
        "id": "hudson-edge-east",
        "name": "Hudson Edge East",
        "species": ["bluefin", "yellowfin"],
        "distance_nm": 72,
        "center_lat": 40.94,
        "center_lng": -71.14,
        "summary": "Warm push crossing a canyon edge with strong overnight stability and visible life.",
        "depth_ft": 820,
    },
    {
        "id": "cartwright-corner",
        "name": "Cartwright Corner",
        "species": ["bluefin", "mahi"],
        "distance_nm": 58,
        "center_lat": 40.88,
        "center_lng": -70.72,
        "summary": "Consistent edge water over structure with moderate current and repeat surface activity.",
        "depth_ft": 540,
    },
    {
        "id": "cox-ledges-south",
        "name": "Cox Ledges South",
        "species": ["bluefin", "yellowfin"],
        "distance_nm": 43,
        "center_lat": 40.71,
        "center_lng": -71.43,
        "summary": "Nearshore structure corridor with a tight thermal edge and dependable bait presence.",
        "depth_ft": 390,
    },
    {
        "id": "butterfish-hole",
        "name": "Butterfish Hole",
        "species": ["yellowfin", "mahi"],
        "distance_nm": 64,
        "center_lat": 40.83,
        "center_lng": -70.51,
        "summary": "Clean blue water around a warmer edge with floating life and favorable drifts.",
        "depth_ft": 610,
    },
    {
        "id": "dip-north",
        "name": "The Dip North",
        "species": ["bluefin", "yellowfin", "mahi"],
        "distance_nm": 77,
        "center_lat": 41.02,
        "center_lng": -70.88,
        "summary": "Offshore seam with strong gradient definition and enough structure influence to hold life.",
        "depth_ft": 960,
    },
]

MOCK_ZONE_ENVIRONMENTAL_SIGNALS = {
    "hudson-edge-east": {
        "sea_surface_temp_f": 69.8,
        "temp_gradient_f_per_nm": 1.6,
        "structure_distance_nm": 2.4,
        "chlorophyll_mg_m3": 0.22,
        "current_speed_kts": 1.8,
        "current_break_index": 0.87,
        "weather_risk_index": 0.24,
    },
    "cartwright-corner": {
        "sea_surface_temp_f": 66.9,
        "temp_gradient_f_per_nm": 1.3,
        "structure_distance_nm": 1.7,
        "chlorophyll_mg_m3": 0.29,
        "current_speed_kts": 1.5,
        "current_break_index": 0.81,
        "weather_risk_index": 0.31,
    },
    "cox-ledges-south": {
        "sea_surface_temp_f": 65.9,
        "temp_gradient_f_per_nm": 1.1,
        "structure_distance_nm": 0.9,
        "chlorophyll_mg_m3": 0.4,
        "current_speed_kts": 1.2,
        "current_break_index": 0.66,
        "weather_risk_index": 0.18,
    },
    "butterfish-hole": {
        "sea_surface_temp_f": 72.1,
        "temp_gradient_f_per_nm": 1.8,
        "structure_distance_nm": 3.8,
        "chlorophyll_mg_m3": 0.16,
        "current_speed_kts": 2.0,
        "current_break_index": 0.92,
        "weather_risk_index": 0.27,
    },
    "dip-north": {
        "sea_surface_temp_f": 68.4,
        "temp_gradient_f_per_nm": 2.1,
        "structure_distance_nm": 2.1,
        "chlorophyll_mg_m3": 0.19,
        "current_speed_kts": 1.9,
        "current_break_index": 0.95,
        "weather_risk_index": 0.36,
    },
}

TRIP_LOGS = [
    {
        "id": "trip-001",
        "date": "2025-09-14",
        "zone_id": "hudson-edge-east",
        "species": ["Yellowfin Tuna"],
        "vessel": "North Star",
        "catch_count": 6,
        "notes": "Started at first light and found steady life along the east side push by 7:20 AM.",
    },
    {
        "id": "trip-002",
        "date": "2025-08-29",
        "zone_id": "cartwright-corner",
        "species": ["Mahi", "Bluefin Tuna"],
        "vessel": "Second Drift",
        "catch_count": 11,
        "notes": "Weed line developed through the afternoon with mahi on floating debris and a late bluefin shot.",
    },
    {
        "id": "trip-003",
        "date": "2025-07-30",
        "zone_id": "cox-ledges-south",
        "species": ["Bluefin Tuna"],
        "vessel": "Outermost",
        "catch_count": 3,
        "notes": "Sparse early marks improved on tide change near contour transitions.",
    },
]
